### ISSUE TITLE
Version 2.2.0 custom filters with operations throw exception

### ISSUE THREAD

**Issue by vrao1020** [Biarity/Sieve#46]
After updating to 2.2.0, I noticed that filters that contain operations no longer work. Filters with no operations seem to work fine though. I downloaded the latest commit of Sieve and ran SieveTests. The default custom filter implementation for `Post` only uses `IsNew` without taking in any operations/values. 

I modified the filter to take in an operation and value:
```
public IQueryable<Post> IsNew(IQueryable<Post> source, string op, string value)
            => source.Where(p => p.LikeCount < Int32.Parse(value) && p.CommentCount < 5);
```
When you send a request using `http://localhost:65136/api/posts/GetAllWithSieve?filters=isnew==100`, the filter is not used. I noticed that `ApplyCustomMethod` in the class `SieveProcessor` uses reflection and calls below:

```
 try
                {
                    result = customMethod.Invoke(parent, parameters)
                        as IQueryable<TEntity>;
                }
```

customMethod.Invoke throws an exception and below is the stacktrace:

```
{System.ArgumentException: Object of type 'System.String[]' cannot be converted to type 'System.String'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sieve.Services.SieveProcessor`3.ApplyCustomMethod[TEntity](IQueryable`1 result, String name, Object parent, Object[] parameters, Object[] optionalParameters) in C:\Users\VR\Downloads\Sieve-master\Sieve-master\Sieve\Services\SieveProcessor.cs:line 376
   at Sieve.Services.SieveProcessor`3.ApplyFiltering[TEntity](TSieveModel model, IQueryable`1 result, Object[] dataForCustomMethods) in C:\Users\VR\Downloads\Sieve-master\Sieve-master\Sieve\Services\SieveProcessor.cs:line 218
   at Sieve.Services.SieveProcessor`3.Apply[TEntity](TSieveModel model, IQueryable`1 source, Object[] dataForCustomMethods, Boolean applyFiltering, Boolean applySorting, Boolean applyPagination) in C:\Users\VR\Downloads\Sieve-master\Sieve-master\Sieve\Services\SieveProcessor.cs:line 127}
```

I reverted my package to 2.1.5 and its working but 2.2.0 does not.

**Comment by Biarity** [comment]
Version 2.2.0 introduced OR logic for operators, so all your custom filters will need to accept a `string[] values` instead of `string value`. You can then replace `value` with `values[0]` to get the first value. Multiple values will be present if the client uses OR logic. I'll add documentation in the README, thanks for spotting this!

**Comment by vrao1020** [comment]
Thanks, didn't realize that. This makes it possible to do some really cool sorts/filters!
